/**
 * HypeMint Contract ABIs
 *
 * Type-safe ABIs for interacting with HypeMint smart contracts
 */

export const HYPE_FACTORY_ABI = [
  {
    type: "function",
    name: "createToken",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "symbol", type: "string", internalType: "string" },
      { name: "imageURI", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "hypeBoostEnabled", type: "bool", internalType: "bool" },
      { name: "slope", type: "uint256", internalType: "uint256" },
      { name: "basePrice", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      { name: "bondingCurveAddress", type: "address", internalType: "address" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getTokenInfo",
    inputs: [{ name: "tokenAddress", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "info",
        type: "tuple",
        internalType: "struct IHypeFactory.TokenInfo",
        components: [
          { name: "tokenAddress", type: "address", internalType: "address" },
          { name: "bondingCurveAddress", type: "address", internalType: "address" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "symbol", type: "string", internalType: "string" },
          { name: "imageURI", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "hypeBoostEnabled", type: "bool", internalType: "bool" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "isBlacklisted", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokensByCreator",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "tokens", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenCount",
    inputs: [],
    outputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creationFee",
    inputs: [],
    outputs: [{ name: "fee", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFee",
    inputs: [],
    outputs: [{ name: "fee", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorFee",
    inputs: [],
    outputs: [{ name: "fee", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "graduationThreshold",
    inputs: [],
    outputs: [{ name: "threshold", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "TokenCreated",
    inputs: [
      { name: "tokenAddress", type: "address", indexed: true, internalType: "address" },
      { name: "bondingCurveAddress", type: "address", indexed: true, internalType: "address" },
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      { name: "symbol", type: "string", indexed: false, internalType: "string" },
      { name: "imageURI", type: "string", indexed: false, internalType: "string" },
      { name: "description", type: "string", indexed: false, internalType: "string" },
      { name: "hypeBoostEnabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
] as const;

export const HYPE_BONDING_CURVE_ABI = [
  {
    type: "function",
    name: "buy",
    inputs: [{ name: "minTokens", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "tokenAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "sell",
    inputs: [
      { name: "tokenAmount", type: "uint256", internalType: "uint256" },
      { name: "minMatic", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "maticAmount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calculateBuy",
    inputs: [{ name: "maticAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "tokenAmount", type: "uint256", internalType: "uint256" },
      { name: "protocolFee", type: "uint256", internalType: "uint256" },
      { name: "creatorFee", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateSell",
    inputs: [{ name: "tokenAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "maticAmount", type: "uint256", internalType: "uint256" },
      { name: "protocolFee", type: "uint256", internalType: "uint256" },
      { name: "creatorFee", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCurrentPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketCap",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reserveBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isGraduated",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHypeBoostConfig",
    inputs: [],
    outputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct IHypeBondingCurve.HypeBoostConfig",
        components: [
          { name: "enabled", type: "bool", internalType: "bool" },
          { name: "maxWalletPercent", type: "uint256", internalType: "uint256" },
          { name: "snipeProtectionBlocks", type: "uint256", internalType: "uint256" },
          { name: "maxBuyPerBlock", type: "uint256", internalType: "uint256" },
          { name: "vestingDuration", type: "uint256", internalType: "uint256" },
          { name: "immediateUnlockPercent", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimVested",
    inputs: [],
    outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getClaimableVested",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVestingInfo",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "info",
        type: "tuple",
        internalType: "struct IHypeBondingCurve.VestingInfo",
        components: [
          { name: "totalAmount", type: "uint256", internalType: "uint256" },
          { name: "claimedAmount", type: "uint256", internalType: "uint256" },
          { name: "startTime", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalFees",
    inputs: [],
    outputs: [
      { name: "protocolFees", type: "uint256", internalType: "uint256" },
      { name: "creatorFees", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "TokenBought",
    inputs: [
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "maticAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "tokenAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newPrice", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "protocolFee", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "creatorFee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenSold",
    inputs: [
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "tokenAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "maticAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "newPrice", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "protocolFee", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "creatorFee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Graduated",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "poolAddress", type: "address", indexed: true, internalType: "address" },
      { name: "liquidityAdded", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "tokensInPool", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const HYPE_TOKEN_ABI = [
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bondingCurve",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "spender", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;
